### ISSUE TITLE
a vs b dotplot error

### ISSUE THREAD

**Issue by lauterbur** [marbl/ModDotPlot#10]
Hi,

When I try to run an a vs b plot using --compare, it produces this error
`TypeError: paired_bed_file_a_vs_b() takes 15 positional arguments but 16 were given`

It looks like there's a disconnect between the definition of the function in  static_plots.py and how it's called in moddotplot.py (line 305)?

**Comment by alexsweeten** [comment]
Hi Elise,

I made some pretty big updates to the ModDotPlot codebase recently. Please pull the latest version and give it a try again. Comparative plots should be working now

Note that interactive mode is now the default way to run ModDotPlot. To produce static images, please run with `moddotplot --static`

Thanks,
Alex
