### ISSUE TITLE
Swapped labels a vs b plot?

### ISSUE THREAD

**Issue by KewinOgink** [marbl/ModDotPlot#29]
Hi thanks for the great tool!

I am testing it and I noticed a difference and it got me confused. I looked at https://github.com/marbl/ModDotPlot/issues/22 but it I downloaded moddotplot last week so it should not be this.

I have a 144kb sequence that I compare to a 239kb sequence using the command

```
for sample in sample17 sample18; do
        moddotplot static \
                -f sample16.fa $sample\
                -o sample16_vs_${sample} --compare-only \
                -w 100 --identity 70 --breakpoints 70 80 90 95 100 --palette Spectral_4 --dpi 1200 \
done
```

The output I get is this.
![image](https://github.com/marbl/ModDotPlot/assets/46783201/a1c517aa-a168-43e6-b9a0-3f2da1532bd8)

The strange thing is I know that sample 16 is 144kb, sample 17 238 and sample 18 172kb, also by looking at their fasta sequences:
![image](https://github.com/marbl/ModDotPlot/assets/46783201/71dd3d81-b136-4932-bcba-2a8644c39afd)

When I look at the bed file it looks like they are swapped, as the header is 
```#query_name	query_start	query_end	reference_name	reference_start	reference_end	perID_by_events```

![image](https://github.com/marbl/ModDotPlot/assets/46783201/78e902d9-4c4e-44bd-add8-cce25b62bb48)

Can this be a bug? Should the labels be switched?

**Comment by alexsweeten** [comment]
Thanks for catching this. Fixed with v0.8.6.
