### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Gon1976** [marbl/ModDotPlot#35]
Hi, I am installing ModDotplot in ubuntu and I have an error:
Collecting tk
  Downloading tk-0.1.0-py3-none-any.whl (3.9 kB)
ERROR: Could not find a version that satisfies the requirement PIL (from moddotplot) (from versions: none)
ERROR: No matching distribution found for PIL

My comands to install were: 
python3.10 -m venv venv
source venv/bin/activate
python3.10 -m pip install .

The complete output:
Processing /home/ggreif/ModDotPlot
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy
  Downloading numpy-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 10.5 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 10.7 MB/s eta 0:00:00
Collecting setproctitle
  Downloading setproctitle-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30 kB)
Collecting plotly
  Downloading plotly-5.24.1-py3-none-any.whl (19.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 8.9 MB/s eta 0:00:00
Collecting patchworklib
  Downloading patchworklib-0.6.4-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 KB 6.8 MB/s eta 0:00:00
Collecting mmh3
  Downloading mmh3-5.0.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.9/88.9 KB 9.4 MB/s eta 0:00:00
Collecting plotnine==0.12.4
  Downloading plotnine-0.12.4-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 10.1 MB/s eta 0:00:00
Collecting pysam
  Downloading pysam-0.22.1-cp310-cp310-manylinux_2_28_x86_64.whl (22.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.0/22.0 MB 4.8 MB/s eta 0:00:00
Collecting dash
  Downloading dash-2.18.1-py3-none-any.whl (7.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 10.4 MB/s eta 0:00:00
Collecting tk
  Downloading tk-0.1.0-py3-none-any.whl (3.9 kB)
ERROR: Could not find a version that satisfies the requirement PIL (from moddotplot) (from versions: none)
ERROR: No matching distribution found for PIL

**Comment by alexsweeten** [comment]
Hi @Gon1976,

This error was caused by a dependency conflict with `PIL`, and has now been patched. Please pull the latest version of ModDotPlot and try again, or simply replace `PIL` with `pillow` in the `pyproject.toml` file.

Thanks,
Alex

**Comment by Gon1976** [comment]
thanks it's work fine now
