### ISSUE TITLE
Legends for static plots?

### ISSUE THREAD

**Issue by abs-yy** [marbl/ModDotPlot#5]
Hi, thanks for the great software!
I've been trying out the static plots and noticed that there are no color legends. Would it be possible to add such legends to these plots?

**Comment by alexsweeten** [comment]
Hi @abs-yy,

Sorry for the late response. ModDotPlot now outputs a histogram alongside each identity heatmap, which can be used as a legend.

**Comment by alexsweeten** [comment]
Addressed above. Closing to clean up issue backlog.
